# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      ghastatus: ${{ steps.step1.outputs.status }}
      lobby: ${{ steps.step2.statuscheck.status }}
    steps:
    - id: step1
      run: echo "::set-output name=status::hello"
    - id: statuscheck
      if: always()
      run: |
        echo "::set-output name=status::world"
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ
        conclusion: neutral
        status: in_progress
        output: |
          {"summary":${{ steps.test.outputs.summary }}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.ghastatus}} ${{needs.job1.outputs.lobby}}
  
